var answersShowing = {
  answer1: false,
  answer2: false,
  answer3: false
};

 var addAnswer = function(answer, button, answerVar) {
  document.getElementById(answer).innerText = answerVar;

  document.getElementById(answer).style.display="none";

  document.getElementById(button).addEventListener("click", function(){toggleAnswer(answer, button, answerVar);});
 };

 var toggleAnswer = function(answer, button, answerVar) {
  if (answersShowing.answerVar === false) {
    document.getElementById(answer).style.display="initial";
    document.getElementById(button).innerText="Hide Answer";
    answersShowing.answerVar = true;
  } else {
    document.getElementById(answer).style.display="none";
    document.getElementById(button).innerText="Show Answer";
    answersShowing.answerVar = false;
  }
};

//Question 1
//If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//
//Find the sum of all the multiples of 3 or 5 below 1000.
( function () {

var answer1 = 0;

for (var i =0; i <1000; i++) {
  if (i % 3 === 0 || i % 5 === 0) {
    answer1 += i;
  }
}

addAnswer("answer1", "button1", answer1);

})();
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
( function () {
  var x = 1;
  var y = 2;
  var z = 0;
  var answer2 = 2;

  for (var i = 0; i < 4000000; i++) {
      z = x + y;
      x = y;
      y = z;
      if (y < 4000000 && (z % 2 === 0) ) {
        answer2 += z;
      } else if (y >= 4000000) {
        break;
      }
  };

addAnswer("answer2", "button2", answer2);
})();

// The prime factors of 13195 are 5, 7, 13 and 29.

// What is the largest prime factor of the number 600851475143 ?


( function () {
  var factorize = 600851475143;
  var primes = [];
  var timesThrough = 0;
  var answer3;
  var findPrime = function(startNumber) {
    for(var i = 0; i < startNumber; i ++) {
      var prime = true;
      for(var j = 0; j < i; j++) {
        if (i % j === 0 && j !== 1) {
          prime = false;
        }
      }
      if (prime === true && ( primes.indexOf(i) === -1 ) && i > 1 && factorize % i ===0) {
          primes.push(i);
          factorize = factorize / i;
          break;
      }
    }

    timesThrough++;
    if (factorize > 1 && timesThrough <3) {
        findPrime(factorize);
    }
    answer3 = factorize;
  };

  findPrime(500);

  addAnswer("answer3", "button3", answer3);
})();

// A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

// Find the largest palindrome made from the product of two 3-digit numbers.

( function () {

  var answer4 = 0;
  var product;
  var reverseProduct;
  var productString;

  function reverse(nString) {
    var o = '';
    for (var i = nString.length - 1; i >= 0; i--) {
      o += nString[i];
      };
    return o;
  };


  for (var i = 100; i < 1000; i++) {
    for(var j = 100; j < 1000; j++) {
      product = i * j;
      productString = product.toString();
      reverseProduct = reverse(productString);
      if (product == reverseProduct && product > answer4) {
        answer4 = product;
      }
    }
  }
  addAnswer("answer4", "button4", answer4);
})();


//5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

//What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

( function () {
  var answer5;
  var bigNum = 500000000;
  var oldI = bigNum;
  var record = 0;
  loop1:
  for(var i = 0; i < bigNum; i ++) {
    loop2:
    for(var j = 1; j < 21; j++) {
      if(i % j === 0) {
        record +=1;
        if(record === 20){
          if (i < oldI && i > 0) {
            answer5 = i;
            oldI = i;
            break loop1;
          } else {
            break;
          }
        }
      } else {
        break;
      }
    }
    record = 0;
  };
  addAnswer("answer5", "button5", answer5);
})();

// The sum of the squares of the first ten natural numbers is,

// 12 + 22 + ... + 102 = 385
// The square of the sum of the first ten natural numbers is,

// (1 + 2 + ... + 10)2 = 552 = 3025
// Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

// Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

( function () {
  var answer6;
  var x = 0;
  var y = 0;

  for(var i = 1; i <= 100; i++){
    x += i * i;
  }
  console.log(x);
  for(var i = 1; i <= 100; i++){
    y += i;
  }

  var z = y * y;
  console.log(z);
  answer6 = z - x;
  console.log(answer6);

  //addAnswer("answer6", "button6", answer6);
})();