var answersShowing = {
  answer1: false,
  answer2: false,
  answer3: false
};

 var addAnswer = function(answer, button, answerVar) {
  document.getElementById(answer).innerText = answerVar;

  document.getElementById(answer).style.display="none";

  document.getElementById(button).addEventListener("click", function(){toggleAnswer(answer, button, answerVar);});
 };

 var toggleAnswer = function(answer, button, answerVar) {
  if (answersShowing.answerVar === false) {
    document.getElementById(answer).style.display="initial";
    document.getElementById(button).innerText="Hide Answer";
    answersShowing.answerVar = true;
  } else {
    document.getElementById(answer).style.display="none";
    document.getElementById(button).innerText="Show Answer";
    answersShowing.answerVar = false;
  }
};

//Question 1
//If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//
//Find the sum of all the multiples of 3 or 5 below 1000.
( function () {

var answer1 = 0;

for (var i =0; i <1000; i++) {
  if (i % 3 === 0 || i % 5 === 0) {
    answer1 += i;
  }
}

addAnswer("answer1", "button1", answer1);

})();
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
( function () {
  var x = 1;
  var y = 2;
  var z = 0;
  var answer2 = 2;

  for (var i = 0; i < 4000000; i++) {
      z = x + y;
      x = y;
      y = z;
      if (y < 4000000 && (z % 2 === 0) ) {
        answer2 += z;
      } else if (y >= 4000000) {
        break;
      }
  };

addAnswer("answer2", "button2", answer2);
})();

// The prime factors of 13195 are 5, 7, 13 and 29.

// What is the largest prime factor of the number 600851475143 ?


( function () {
  var factorize = 600851475143;
  var primes = [];
  var timesThrough = 0;
  var answer3;
  var findPrime = function(startNumber) {
    for(var i = 0; i < startNumber; i ++) {
      var prime = true;
      for(var j = 0; j < i; j++) {
        if (i % j === 0 && j !== 1) {
          prime = false;
        }
      }
      if (prime === true && ( primes.indexOf(i) === -1 ) && i > 1 && factorize % i ===0) {
          primes.push(i);
          factorize = factorize / i;
          break;
      }
    }

    timesThrough++;
    if (factorize > 1 && timesThrough <3) {
        findPrime(factorize);
    }
    answer3 = factorize;
  };

  findPrime(500);

addAnswer("answer3", "button3", answer3);
})();